### PR TITLE
Static IP and A2P Voice App key

### PR DESCRIPTION
**Pull request by babtist**
I have added description of static IP and A2P Voice application key.
These are new properties on the subscription and shall be able to set when creating a subscription as well as when doing PATCH

### CODE REVIEW

**Comment by symkrister** [comment]
Top header says "Change ODB Profile" in  change_a2p_voice_app_key.md  and  change_static_ip.md

**Review by t0mh0l — COMMENTED** [review]
Propose to update use-case: GET basic subscription info with the new attributes (ODB, voice key and static ip).
We have not got a quote from AN yet, not sure if we ECC will deliver static IP and voice in same Sprint. We may have to release the API doc in steps.

**Comment by babtist** [comment]
I fixed the typos in the headers in  change_a2p_voice_app_key.md and change_static_ip.md

**Comment by babtist** [comment]
@Tomas: do you mean that we shouldn't include the Static IP description in the ECC API now?

**Comment by t0mh0l** [comment]
Yes, lets not publish it before ECC/IoT offers the service.

/Tomas

**Pull request merged**
